/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUnauthorizedRouteImport } from './routes/_authenticated/unauthorized'
import { Route as AuthenticatedAccountingClientPricingRouteImport } from './routes/_authenticated/accounting/client-pricing'
import { Route as AuthenticatedAccountingItemsRouteImport } from './routes/_authenticated/accounting/items'
import { Route as AuthenticatedAccountingPaymentHistoryRouteImport } from './routes/_authenticated/accounting/payment-history'
import { Route as AuthenticatedAccountingPendingPaymentsRouteImport } from './routes/_authenticated/accounting/pending-payments'
import { Route as AuthenticatedAccountingPendingPricingRouteImport } from './routes/_authenticated/accounting/pending-pricing'
import { Route as AuthenticatedAdminActivityLogRouteImport } from './routes/_authenticated/admin/activity-log'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated/admin/branches'
import { Route as AuthenticatedAdminClientAccountsRouteImport } from './routes/_authenticated/admin/client-accounts'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin/clients'
import { Route as AuthenticatedAdminRolePermissionsRouteImport } from './routes/_authenticated/admin/role-permissions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin/staff'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin/suppliers'
import { Route as AuthenticatedInventoryExpiringRouteImport } from './routes/_authenticated/inventory/expiring'
import { Route as AuthenticatedInventoryLowStockRouteImport } from './routes/_authenticated/inventory/low-stock'
import { Route as AuthenticatedItemsIndexRouteImport } from './routes/_authenticated/items/index'
import { Route as AuthenticatedItemsCategoriesRouteImport } from './routes/_authenticated/items/categories'
import { Route as AuthenticatedItemsNewRouteImport } from './routes/_authenticated/items/new'
import { Route as AuthenticatedItemsUnitsRouteImport } from './routes/_authenticated/items/units'
import { Route as AuthenticatedLogisticsDeliveryHistoryRouteImport } from './routes/_authenticated/logistics/delivery-history'
import { Route as AuthenticatedLogisticsIncomingOrdersRouteImport } from './routes/_authenticated/logistics/incoming-orders'
import { Route as AuthenticatedLogisticsReadyToDeliverRouteImport } from './routes/_authenticated/logistics/ready-to-deliver'
import { Route as AuthenticatedPurchasingPurchaseOrdersRouteImport } from './routes/_authenticated/purchasing/purchase-orders'
import { Route as AuthenticatedPurchasingStockReceivingRouteImport } from './routes/_authenticated/purchasing/stock-receiving'
import { Route as AuthenticatedPurchasingSuppliersRouteImport } from './routes/_authenticated/purchasing/suppliers'
import { Route as AuthenticatedSalesClientsRouteImport } from './routes/_authenticated/sales/clients'
import { Route as AuthenticatedSalesClientsAnalyticsRouteImport } from './routes/_authenticated/sales/clients-analytics'
import { Route as AuthenticatedSalesCofsRouteImport } from './routes/_authenticated/sales/cofs'
import { Route as AuthenticatedSalesDiscountsRouteImport } from './routes/_authenticated/sales/discounts'
import { Route as AuthenticatedSalesDispatchRouteImport } from './routes/_authenticated/sales/dispatch'
import { Route as AuthenticatedSalesIntakeRouteImport } from './routes/_authenticated/sales/intake'
import { Route as AuthenticatedSalesItemsRouteImport } from './routes/_authenticated/sales/items'
import { Route as AuthenticatedSalesItemsExpiryRouteImport } from './routes/_authenticated/sales/items-expiry'
import { Route as AuthenticatedSuperAdminBranchDashboardsRouteImport } from './routes/_authenticated/super-admin/branch-dashboards'
import { Route as AuthenticatedSuperAdminBranchesRouteImport } from './routes/_authenticated/super-admin/branches'
import { Route as AuthenticatedSuperAdminClientsRouteImport } from './routes/_authenticated/super-admin/clients'
import { Route as AuthenticatedSuperAdminCompanyAnalyticsRouteImport } from './routes/_authenticated/super-admin/company-analytics'
import { Route as AuthenticatedSuperAdminCompareBranchesRouteImport } from './routes/_authenticated/super-admin/compare-branches'
import { Route as AuthenticatedSuperAdminPurchasesOverviewRouteImport } from './routes/_authenticated/super-admin/purchases-overview'
import { Route as AuthenticatedSuperAdminRoleAssignmentRouteImport } from './routes/_authenticated/super-admin/role-assignment'
import { Route as AuthenticatedSuperAdminSalesOverviewRouteImport } from './routes/_authenticated/super-admin/sales-overview'
import { Route as AuthenticatedItemsItemIdIndexRouteImport } from './routes/_authenticated/items/$itemId/index'
import { Route as AuthenticatedItemsItemIdEditRouteImport } from './routes/_authenticated/items/$itemId/edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnauthorizedRoute =
  AuthenticatedUnauthorizedRouteImport.update({
    id: '/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingClientPricingRoute =
  AuthenticatedAccountingClientPricingRouteImport.update({
    id: '/accounting/client-pricing',
    path: '/accounting/client-pricing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingItemsRoute =
  AuthenticatedAccountingItemsRouteImport.update({
    id: '/accounting/items',
    path: '/accounting/items',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingPaymentHistoryRoute =
  AuthenticatedAccountingPaymentHistoryRouteImport.update({
    id: '/accounting/payment-history',
    path: '/accounting/payment-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingPendingPaymentsRoute =
  AuthenticatedAccountingPendingPaymentsRouteImport.update({
    id: '/accounting/pending-payments',
    path: '/accounting/pending-payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountingPendingPricingRoute =
  AuthenticatedAccountingPendingPricingRouteImport.update({
    id: '/accounting/pending-pricing',
    path: '/accounting/pending-pricing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminActivityLogRoute =
  AuthenticatedAdminActivityLogRouteImport.update({
    id: '/admin/activity-log',
    path: '/admin/activity-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/admin/branches',
    path: '/admin/branches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientAccountsRoute =
  AuthenticatedAdminClientAccountsRouteImport.update({
    id: '/admin/client-accounts',
    path: '/admin/client-accounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/admin/clients',
    path: '/admin/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRolePermissionsRoute =
  AuthenticatedAdminRolePermissionsRouteImport.update({
    id: '/admin/role-permissions',
    path: '/admin/role-permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/admin/suppliers',
    path: '/admin/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryExpiringRoute =
  AuthenticatedInventoryExpiringRouteImport.update({
    id: '/inventory/expiring',
    path: '/inventory/expiring',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryLowStockRoute =
  AuthenticatedInventoryLowStockRouteImport.update({
    id: '/inventory/low-stock',
    path: '/inventory/low-stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsIndexRoute = AuthenticatedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsCategoriesRoute =
  AuthenticatedItemsCategoriesRouteImport.update({
    id: '/items/categories',
    path: '/items/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsNewRoute = AuthenticatedItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedItemsUnitsRoute = AuthenticatedItemsUnitsRouteImport.update({
  id: '/items/units',
  path: '/items/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogisticsDeliveryHistoryRoute =
  AuthenticatedLogisticsDeliveryHistoryRouteImport.update({
    id: '/logistics/delivery-history',
    path: '/logistics/delivery-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsIncomingOrdersRoute =
  AuthenticatedLogisticsIncomingOrdersRouteImport.update({
    id: '/logistics/incoming-orders',
    path: '/logistics/incoming-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogisticsReadyToDeliverRoute =
  AuthenticatedLogisticsReadyToDeliverRouteImport.update({
    id: '/logistics/ready-to-deliver',
    path: '/logistics/ready-to-deliver',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasingPurchaseOrdersRoute =
  AuthenticatedPurchasingPurchaseOrdersRouteImport.update({
    id: '/purchasing/purchase-orders',
    path: '/purchasing/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasingStockReceivingRoute =
  AuthenticatedPurchasingStockReceivingRouteImport.update({
    id: '/purchasing/stock-receiving',
    path: '/purchasing/stock-receiving',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasingSuppliersRoute =
  AuthenticatedPurchasingSuppliersRouteImport.update({
    id: '/purchasing/suppliers',
    path: '/purchasing/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesClientsRoute =
  AuthenticatedSalesClientsRouteImport.update({
    id: '/sales/clients',
    path: '/sales/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesClientsAnalyticsRoute =
  AuthenticatedSalesClientsAnalyticsRouteImport.update({
    id: '/sales/clients-analytics',
    path: '/sales/clients-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesCofsRoute = AuthenticatedSalesCofsRouteImport.update({
  id: '/sales/cofs',
  path: '/sales/cofs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesDiscountsRoute =
  AuthenticatedSalesDiscountsRouteImport.update({
    id: '/sales/discounts',
    path: '/sales/discounts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesDispatchRoute =
  AuthenticatedSalesDispatchRouteImport.update({
    id: '/sales/dispatch',
    path: '/sales/dispatch',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesIntakeRoute =
  AuthenticatedSalesIntakeRouteImport.update({
    id: '/sales/intake',
    path: '/sales/intake',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesItemsRoute = AuthenticatedSalesItemsRouteImport.update({
  id: '/sales/items',
  path: '/sales/items',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSalesItemsExpiryRoute =
  AuthenticatedSalesItemsExpiryRouteImport.update({
    id: '/sales/items-expiry',
    path: '/sales/items-expiry',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminBranchDashboardsRoute =
  AuthenticatedSuperAdminBranchDashboardsRouteImport.update({
    id: '/super-admin/branch-dashboards',
    path: '/super-admin/branch-dashboards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminBranchesRoute =
  AuthenticatedSuperAdminBranchesRouteImport.update({
    id: '/super-admin/branches',
    path: '/super-admin/branches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminClientsRoute =
  AuthenticatedSuperAdminClientsRouteImport.update({
    id: '/super-admin/clients',
    path: '/super-admin/clients',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminCompanyAnalyticsRoute =
  AuthenticatedSuperAdminCompanyAnalyticsRouteImport.update({
    id: '/super-admin/company-analytics',
    path: '/super-admin/company-analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminCompareBranchesRoute =
  AuthenticatedSuperAdminCompareBranchesRouteImport.update({
    id: '/super-admin/compare-branches',
    path: '/super-admin/compare-branches',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminPurchasesOverviewRoute =
  AuthenticatedSuperAdminPurchasesOverviewRouteImport.update({
    id: '/super-admin/purchases-overview',
    path: '/super-admin/purchases-overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminRoleAssignmentRoute =
  AuthenticatedSuperAdminRoleAssignmentRouteImport.update({
    id: '/super-admin/role-assignment',
    path: '/super-admin/role-assignment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuperAdminSalesOverviewRoute =
  AuthenticatedSuperAdminSalesOverviewRouteImport.update({
    id: '/super-admin/sales-overview',
    path: '/super-admin/sales-overview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdIndexRoute =
  AuthenticatedItemsItemIdIndexRouteImport.update({
    id: '/items/$itemId/',
    path: '/items/$itemId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedItemsItemIdEditRoute =
  AuthenticatedItemsItemIdEditRouteImport.update({
    id: '/items/$itemId/edit',
    path: '/items/$itemId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/accounting/client-pricing': typeof AuthenticatedAccountingClientPricingRoute
  '/accounting/items': typeof AuthenticatedAccountingItemsRoute
  '/accounting/payment-history': typeof AuthenticatedAccountingPaymentHistoryRoute
  '/accounting/pending-payments': typeof AuthenticatedAccountingPendingPaymentsRoute
  '/accounting/pending-pricing': typeof AuthenticatedAccountingPendingPricingRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/client-accounts': typeof AuthenticatedAdminClientAccountsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/role-permissions': typeof AuthenticatedAdminRolePermissionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/inventory/expiring': typeof AuthenticatedInventoryExpiringRoute
  '/inventory/low-stock': typeof AuthenticatedInventoryLowStockRoute
  '/items/categories': typeof AuthenticatedItemsCategoriesRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/items/units': typeof AuthenticatedItemsUnitsRoute
  '/logistics/delivery-history': typeof AuthenticatedLogisticsDeliveryHistoryRoute
  '/logistics/incoming-orders': typeof AuthenticatedLogisticsIncomingOrdersRoute
  '/logistics/ready-to-deliver': typeof AuthenticatedLogisticsReadyToDeliverRoute
  '/purchasing/purchase-orders': typeof AuthenticatedPurchasingPurchaseOrdersRoute
  '/purchasing/stock-receiving': typeof AuthenticatedPurchasingStockReceivingRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/sales/clients': typeof AuthenticatedSalesClientsRoute
  '/sales/clients-analytics': typeof AuthenticatedSalesClientsAnalyticsRoute
  '/sales/cofs': typeof AuthenticatedSalesCofsRoute
  '/sales/discounts': typeof AuthenticatedSalesDiscountsRoute
  '/sales/dispatch': typeof AuthenticatedSalesDispatchRoute
  '/sales/intake': typeof AuthenticatedSalesIntakeRoute
  '/sales/items': typeof AuthenticatedSalesItemsRoute
  '/sales/items-expiry': typeof AuthenticatedSalesItemsExpiryRoute
  '/super-admin/branch-dashboards': typeof AuthenticatedSuperAdminBranchDashboardsRoute
  '/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/super-admin/clients': typeof AuthenticatedSuperAdminClientsRoute
  '/super-admin/company-analytics': typeof AuthenticatedSuperAdminCompanyAnalyticsRoute
  '/super-admin/compare-branches': typeof AuthenticatedSuperAdminCompareBranchesRoute
  '/super-admin/purchases-overview': typeof AuthenticatedSuperAdminPurchasesOverviewRoute
  '/super-admin/role-assignment': typeof AuthenticatedSuperAdminRoleAssignmentRoute
  '/super-admin/sales-overview': typeof AuthenticatedSuperAdminSalesOverviewRoute
  '/items/': typeof AuthenticatedItemsIndexRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/items/$itemId/': typeof AuthenticatedItemsItemIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/': typeof AuthenticatedIndexRoute
  '/accounting/client-pricing': typeof AuthenticatedAccountingClientPricingRoute
  '/accounting/items': typeof AuthenticatedAccountingItemsRoute
  '/accounting/payment-history': typeof AuthenticatedAccountingPaymentHistoryRoute
  '/accounting/pending-payments': typeof AuthenticatedAccountingPendingPaymentsRoute
  '/accounting/pending-pricing': typeof AuthenticatedAccountingPendingPricingRoute
  '/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/client-accounts': typeof AuthenticatedAdminClientAccountsRoute
  '/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/admin/role-permissions': typeof AuthenticatedAdminRolePermissionsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/inventory/expiring': typeof AuthenticatedInventoryExpiringRoute
  '/inventory/low-stock': typeof AuthenticatedInventoryLowStockRoute
  '/items/categories': typeof AuthenticatedItemsCategoriesRoute
  '/items/new': typeof AuthenticatedItemsNewRoute
  '/items/units': typeof AuthenticatedItemsUnitsRoute
  '/logistics/delivery-history': typeof AuthenticatedLogisticsDeliveryHistoryRoute
  '/logistics/incoming-orders': typeof AuthenticatedLogisticsIncomingOrdersRoute
  '/logistics/ready-to-deliver': typeof AuthenticatedLogisticsReadyToDeliverRoute
  '/purchasing/purchase-orders': typeof AuthenticatedPurchasingPurchaseOrdersRoute
  '/purchasing/stock-receiving': typeof AuthenticatedPurchasingStockReceivingRoute
  '/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/sales/clients': typeof AuthenticatedSalesClientsRoute
  '/sales/clients-analytics': typeof AuthenticatedSalesClientsAnalyticsRoute
  '/sales/cofs': typeof AuthenticatedSalesCofsRoute
  '/sales/discounts': typeof AuthenticatedSalesDiscountsRoute
  '/sales/dispatch': typeof AuthenticatedSalesDispatchRoute
  '/sales/intake': typeof AuthenticatedSalesIntakeRoute
  '/sales/items': typeof AuthenticatedSalesItemsRoute
  '/sales/items-expiry': typeof AuthenticatedSalesItemsExpiryRoute
  '/super-admin/branch-dashboards': typeof AuthenticatedSuperAdminBranchDashboardsRoute
  '/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/super-admin/clients': typeof AuthenticatedSuperAdminClientsRoute
  '/super-admin/company-analytics': typeof AuthenticatedSuperAdminCompanyAnalyticsRoute
  '/super-admin/compare-branches': typeof AuthenticatedSuperAdminCompareBranchesRoute
  '/super-admin/purchases-overview': typeof AuthenticatedSuperAdminPurchasesOverviewRoute
  '/super-admin/role-assignment': typeof AuthenticatedSuperAdminRoleAssignmentRoute
  '/super-admin/sales-overview': typeof AuthenticatedSuperAdminSalesOverviewRoute
  '/items': typeof AuthenticatedItemsIndexRoute
  '/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/items/$itemId': typeof AuthenticatedItemsItemIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/unauthorized': typeof AuthenticatedUnauthorizedRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/accounting/client-pricing': typeof AuthenticatedAccountingClientPricingRoute
  '/_authenticated/accounting/items': typeof AuthenticatedAccountingItemsRoute
  '/_authenticated/accounting/payment-history': typeof AuthenticatedAccountingPaymentHistoryRoute
  '/_authenticated/accounting/pending-payments': typeof AuthenticatedAccountingPendingPaymentsRoute
  '/_authenticated/accounting/pending-pricing': typeof AuthenticatedAccountingPendingPricingRoute
  '/_authenticated/admin/activity-log': typeof AuthenticatedAdminActivityLogRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/client-accounts': typeof AuthenticatedAdminClientAccountsRoute
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRoute
  '/_authenticated/admin/role-permissions': typeof AuthenticatedAdminRolePermissionsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/inventory/expiring': typeof AuthenticatedInventoryExpiringRoute
  '/_authenticated/inventory/low-stock': typeof AuthenticatedInventoryLowStockRoute
  '/_authenticated/items/categories': typeof AuthenticatedItemsCategoriesRoute
  '/_authenticated/items/new': typeof AuthenticatedItemsNewRoute
  '/_authenticated/items/units': typeof AuthenticatedItemsUnitsRoute
  '/_authenticated/logistics/delivery-history': typeof AuthenticatedLogisticsDeliveryHistoryRoute
  '/_authenticated/logistics/incoming-orders': typeof AuthenticatedLogisticsIncomingOrdersRoute
  '/_authenticated/logistics/ready-to-deliver': typeof AuthenticatedLogisticsReadyToDeliverRoute
  '/_authenticated/purchasing/purchase-orders': typeof AuthenticatedPurchasingPurchaseOrdersRoute
  '/_authenticated/purchasing/stock-receiving': typeof AuthenticatedPurchasingStockReceivingRoute
  '/_authenticated/purchasing/suppliers': typeof AuthenticatedPurchasingSuppliersRoute
  '/_authenticated/sales/clients': typeof AuthenticatedSalesClientsRoute
  '/_authenticated/sales/clients-analytics': typeof AuthenticatedSalesClientsAnalyticsRoute
  '/_authenticated/sales/cofs': typeof AuthenticatedSalesCofsRoute
  '/_authenticated/sales/discounts': typeof AuthenticatedSalesDiscountsRoute
  '/_authenticated/sales/dispatch': typeof AuthenticatedSalesDispatchRoute
  '/_authenticated/sales/intake': typeof AuthenticatedSalesIntakeRoute
  '/_authenticated/sales/items': typeof AuthenticatedSalesItemsRoute
  '/_authenticated/sales/items-expiry': typeof AuthenticatedSalesItemsExpiryRoute
  '/_authenticated/super-admin/branch-dashboards': typeof AuthenticatedSuperAdminBranchDashboardsRoute
  '/_authenticated/super-admin/branches': typeof AuthenticatedSuperAdminBranchesRoute
  '/_authenticated/super-admin/clients': typeof AuthenticatedSuperAdminClientsRoute
  '/_authenticated/super-admin/company-analytics': typeof AuthenticatedSuperAdminCompanyAnalyticsRoute
  '/_authenticated/super-admin/compare-branches': typeof AuthenticatedSuperAdminCompareBranchesRoute
  '/_authenticated/super-admin/purchases-overview': typeof AuthenticatedSuperAdminPurchasesOverviewRoute
  '/_authenticated/super-admin/role-assignment': typeof AuthenticatedSuperAdminRoleAssignmentRoute
  '/_authenticated/super-admin/sales-overview': typeof AuthenticatedSuperAdminSalesOverviewRoute
  '/_authenticated/items/': typeof AuthenticatedItemsIndexRoute
  '/_authenticated/items/$itemId/edit': typeof AuthenticatedItemsItemIdEditRoute
  '/_authenticated/items/$itemId/': typeof AuthenticatedItemsItemIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/accounting/client-pricing'
    | '/accounting/items'
    | '/accounting/payment-history'
    | '/accounting/pending-payments'
    | '/accounting/pending-pricing'
    | '/admin/activity-log'
    | '/admin/branches'
    | '/admin/client-accounts'
    | '/admin/clients'
    | '/admin/role-permissions'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/suppliers'
    | '/inventory/expiring'
    | '/inventory/low-stock'
    | '/items/categories'
    | '/items/new'
    | '/items/units'
    | '/logistics/delivery-history'
    | '/logistics/incoming-orders'
    | '/logistics/ready-to-deliver'
    | '/purchasing/purchase-orders'
    | '/purchasing/stock-receiving'
    | '/purchasing/suppliers'
    | '/sales/clients'
    | '/sales/clients-analytics'
    | '/sales/cofs'
    | '/sales/discounts'
    | '/sales/dispatch'
    | '/sales/intake'
    | '/sales/items'
    | '/sales/items-expiry'
    | '/super-admin/branch-dashboards'
    | '/super-admin/branches'
    | '/super-admin/clients'
    | '/super-admin/company-analytics'
    | '/super-admin/compare-branches'
    | '/super-admin/purchases-overview'
    | '/super-admin/role-assignment'
    | '/super-admin/sales-overview'
    | '/items/'
    | '/items/$itemId/edit'
    | '/items/$itemId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/unauthorized'
    | '/'
    | '/accounting/client-pricing'
    | '/accounting/items'
    | '/accounting/payment-history'
    | '/accounting/pending-payments'
    | '/accounting/pending-pricing'
    | '/admin/activity-log'
    | '/admin/branches'
    | '/admin/client-accounts'
    | '/admin/clients'
    | '/admin/role-permissions'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/suppliers'
    | '/inventory/expiring'
    | '/inventory/low-stock'
    | '/items/categories'
    | '/items/new'
    | '/items/units'
    | '/logistics/delivery-history'
    | '/logistics/incoming-orders'
    | '/logistics/ready-to-deliver'
    | '/purchasing/purchase-orders'
    | '/purchasing/stock-receiving'
    | '/purchasing/suppliers'
    | '/sales/clients'
    | '/sales/clients-analytics'
    | '/sales/cofs'
    | '/sales/discounts'
    | '/sales/dispatch'
    | '/sales/intake'
    | '/sales/items'
    | '/sales/items-expiry'
    | '/super-admin/branch-dashboards'
    | '/super-admin/branches'
    | '/super-admin/clients'
    | '/super-admin/company-analytics'
    | '/super-admin/compare-branches'
    | '/super-admin/purchases-overview'
    | '/super-admin/role-assignment'
    | '/super-admin/sales-overview'
    | '/items'
    | '/items/$itemId/edit'
    | '/items/$itemId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/unauthorized'
    | '/_authenticated/'
    | '/_authenticated/accounting/client-pricing'
    | '/_authenticated/accounting/items'
    | '/_authenticated/accounting/payment-history'
    | '/_authenticated/accounting/pending-payments'
    | '/_authenticated/accounting/pending-pricing'
    | '/_authenticated/admin/activity-log'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/client-accounts'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/role-permissions'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/inventory/expiring'
    | '/_authenticated/inventory/low-stock'
    | '/_authenticated/items/categories'
    | '/_authenticated/items/new'
    | '/_authenticated/items/units'
    | '/_authenticated/logistics/delivery-history'
    | '/_authenticated/logistics/incoming-orders'
    | '/_authenticated/logistics/ready-to-deliver'
    | '/_authenticated/purchasing/purchase-orders'
    | '/_authenticated/purchasing/stock-receiving'
    | '/_authenticated/purchasing/suppliers'
    | '/_authenticated/sales/clients'
    | '/_authenticated/sales/clients-analytics'
    | '/_authenticated/sales/cofs'
    | '/_authenticated/sales/discounts'
    | '/_authenticated/sales/dispatch'
    | '/_authenticated/sales/intake'
    | '/_authenticated/sales/items'
    | '/_authenticated/sales/items-expiry'
    | '/_authenticated/super-admin/branch-dashboards'
    | '/_authenticated/super-admin/branches'
    | '/_authenticated/super-admin/clients'
    | '/_authenticated/super-admin/company-analytics'
    | '/_authenticated/super-admin/compare-branches'
    | '/_authenticated/super-admin/purchases-overview'
    | '/_authenticated/super-admin/role-assignment'
    | '/_authenticated/super-admin/sales-overview'
    | '/_authenticated/items/'
    | '/_authenticated/items/$itemId/edit'
    | '/_authenticated/items/$itemId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/unauthorized': {
      id: '/_authenticated/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof AuthenticatedUnauthorizedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/client-pricing': {
      id: '/_authenticated/accounting/client-pricing'
      path: '/accounting/client-pricing'
      fullPath: '/accounting/client-pricing'
      preLoaderRoute: typeof AuthenticatedAccountingClientPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/items': {
      id: '/_authenticated/accounting/items'
      path: '/accounting/items'
      fullPath: '/accounting/items'
      preLoaderRoute: typeof AuthenticatedAccountingItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/payment-history': {
      id: '/_authenticated/accounting/payment-history'
      path: '/accounting/payment-history'
      fullPath: '/accounting/payment-history'
      preLoaderRoute: typeof AuthenticatedAccountingPaymentHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/pending-payments': {
      id: '/_authenticated/accounting/pending-payments'
      path: '/accounting/pending-payments'
      fullPath: '/accounting/pending-payments'
      preLoaderRoute: typeof AuthenticatedAccountingPendingPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounting/pending-pricing': {
      id: '/_authenticated/accounting/pending-pricing'
      path: '/accounting/pending-pricing'
      fullPath: '/accounting/pending-pricing'
      preLoaderRoute: typeof AuthenticatedAccountingPendingPricingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/activity-log': {
      id: '/_authenticated/admin/activity-log'
      path: '/admin/activity-log'
      fullPath: '/admin/activity-log'
      preLoaderRoute: typeof AuthenticatedAdminActivityLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/admin/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/client-accounts': {
      id: '/_authenticated/admin/client-accounts'
      path: '/admin/client-accounts'
      fullPath: '/admin/client-accounts'
      preLoaderRoute: typeof AuthenticatedAdminClientAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/role-permissions': {
      id: '/_authenticated/admin/role-permissions'
      path: '/admin/role-permissions'
      fullPath: '/admin/role-permissions'
      preLoaderRoute: typeof AuthenticatedAdminRolePermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/expiring': {
      id: '/_authenticated/inventory/expiring'
      path: '/inventory/expiring'
      fullPath: '/inventory/expiring'
      preLoaderRoute: typeof AuthenticatedInventoryExpiringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/low-stock': {
      id: '/_authenticated/inventory/low-stock'
      path: '/inventory/low-stock'
      fullPath: '/inventory/low-stock'
      preLoaderRoute: typeof AuthenticatedInventoryLowStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/': {
      id: '/_authenticated/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AuthenticatedItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/categories': {
      id: '/_authenticated/items/categories'
      path: '/items/categories'
      fullPath: '/items/categories'
      preLoaderRoute: typeof AuthenticatedItemsCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/new': {
      id: '/_authenticated/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof AuthenticatedItemsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/units': {
      id: '/_authenticated/items/units'
      path: '/items/units'
      fullPath: '/items/units'
      preLoaderRoute: typeof AuthenticatedItemsUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/delivery-history': {
      id: '/_authenticated/logistics/delivery-history'
      path: '/logistics/delivery-history'
      fullPath: '/logistics/delivery-history'
      preLoaderRoute: typeof AuthenticatedLogisticsDeliveryHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/incoming-orders': {
      id: '/_authenticated/logistics/incoming-orders'
      path: '/logistics/incoming-orders'
      fullPath: '/logistics/incoming-orders'
      preLoaderRoute: typeof AuthenticatedLogisticsIncomingOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logistics/ready-to-deliver': {
      id: '/_authenticated/logistics/ready-to-deliver'
      path: '/logistics/ready-to-deliver'
      fullPath: '/logistics/ready-to-deliver'
      preLoaderRoute: typeof AuthenticatedLogisticsReadyToDeliverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchasing/purchase-orders': {
      id: '/_authenticated/purchasing/purchase-orders'
      path: '/purchasing/purchase-orders'
      fullPath: '/purchasing/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchasingPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchasing/stock-receiving': {
      id: '/_authenticated/purchasing/stock-receiving'
      path: '/purchasing/stock-receiving'
      fullPath: '/purchasing/stock-receiving'
      preLoaderRoute: typeof AuthenticatedPurchasingStockReceivingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchasing/suppliers': {
      id: '/_authenticated/purchasing/suppliers'
      path: '/purchasing/suppliers'
      fullPath: '/purchasing/suppliers'
      preLoaderRoute: typeof AuthenticatedPurchasingSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/clients': {
      id: '/_authenticated/sales/clients'
      path: '/sales/clients'
      fullPath: '/sales/clients'
      preLoaderRoute: typeof AuthenticatedSalesClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/clients-analytics': {
      id: '/_authenticated/sales/clients-analytics'
      path: '/sales/clients-analytics'
      fullPath: '/sales/clients-analytics'
      preLoaderRoute: typeof AuthenticatedSalesClientsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/cofs': {
      id: '/_authenticated/sales/cofs'
      path: '/sales/cofs'
      fullPath: '/sales/cofs'
      preLoaderRoute: typeof AuthenticatedSalesCofsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/discounts': {
      id: '/_authenticated/sales/discounts'
      path: '/sales/discounts'
      fullPath: '/sales/discounts'
      preLoaderRoute: typeof AuthenticatedSalesDiscountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/dispatch': {
      id: '/_authenticated/sales/dispatch'
      path: '/sales/dispatch'
      fullPath: '/sales/dispatch'
      preLoaderRoute: typeof AuthenticatedSalesDispatchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/intake': {
      id: '/_authenticated/sales/intake'
      path: '/sales/intake'
      fullPath: '/sales/intake'
      preLoaderRoute: typeof AuthenticatedSalesIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/items': {
      id: '/_authenticated/sales/items'
      path: '/sales/items'
      fullPath: '/sales/items'
      preLoaderRoute: typeof AuthenticatedSalesItemsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/items-expiry': {
      id: '/_authenticated/sales/items-expiry'
      path: '/sales/items-expiry'
      fullPath: '/sales/items-expiry'
      preLoaderRoute: typeof AuthenticatedSalesItemsExpiryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/branch-dashboards': {
      id: '/_authenticated/super-admin/branch-dashboards'
      path: '/super-admin/branch-dashboards'
      fullPath: '/super-admin/branch-dashboards'
      preLoaderRoute: typeof AuthenticatedSuperAdminBranchDashboardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/branches': {
      id: '/_authenticated/super-admin/branches'
      path: '/super-admin/branches'
      fullPath: '/super-admin/branches'
      preLoaderRoute: typeof AuthenticatedSuperAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/clients': {
      id: '/_authenticated/super-admin/clients'
      path: '/super-admin/clients'
      fullPath: '/super-admin/clients'
      preLoaderRoute: typeof AuthenticatedSuperAdminClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/company-analytics': {
      id: '/_authenticated/super-admin/company-analytics'
      path: '/super-admin/company-analytics'
      fullPath: '/super-admin/company-analytics'
      preLoaderRoute: typeof AuthenticatedSuperAdminCompanyAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/compare-branches': {
      id: '/_authenticated/super-admin/compare-branches'
      path: '/super-admin/compare-branches'
      fullPath: '/super-admin/compare-branches'
      preLoaderRoute: typeof AuthenticatedSuperAdminCompareBranchesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/purchases-overview': {
      id: '/_authenticated/super-admin/purchases-overview'
      path: '/super-admin/purchases-overview'
      fullPath: '/super-admin/purchases-overview'
      preLoaderRoute: typeof AuthenticatedSuperAdminPurchasesOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/role-assignment': {
      id: '/_authenticated/super-admin/role-assignment'
      path: '/super-admin/role-assignment'
      fullPath: '/super-admin/role-assignment'
      preLoaderRoute: typeof AuthenticatedSuperAdminRoleAssignmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/super-admin/sales-overview': {
      id: '/_authenticated/super-admin/sales-overview'
      path: '/super-admin/sales-overview'
      fullPath: '/super-admin/sales-overview'
      preLoaderRoute: typeof AuthenticatedSuperAdminSalesOverviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId/': {
      id: '/_authenticated/items/$itemId/'
      path: '/items/$itemId'
      fullPath: '/items/$itemId/'
      preLoaderRoute: typeof AuthenticatedItemsItemIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/items/$itemId/edit': {
      id: '/_authenticated/items/$itemId/edit'
      path: '/items/$itemId/edit'
      fullPath: '/items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUnauthorizedRoute: typeof AuthenticatedUnauthorizedRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountingClientPricingRoute: typeof AuthenticatedAccountingClientPricingRoute
  AuthenticatedAccountingItemsRoute: typeof AuthenticatedAccountingItemsRoute
  AuthenticatedAccountingPaymentHistoryRoute: typeof AuthenticatedAccountingPaymentHistoryRoute
  AuthenticatedAccountingPendingPaymentsRoute: typeof AuthenticatedAccountingPendingPaymentsRoute
  AuthenticatedAccountingPendingPricingRoute: typeof AuthenticatedAccountingPendingPricingRoute
  AuthenticatedAdminActivityLogRoute: typeof AuthenticatedAdminActivityLogRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminClientAccountsRoute: typeof AuthenticatedAdminClientAccountsRoute
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRoute
  AuthenticatedAdminRolePermissionsRoute: typeof AuthenticatedAdminRolePermissionsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedInventoryExpiringRoute: typeof AuthenticatedInventoryExpiringRoute
  AuthenticatedInventoryLowStockRoute: typeof AuthenticatedInventoryLowStockRoute
  AuthenticatedItemsCategoriesRoute: typeof AuthenticatedItemsCategoriesRoute
  AuthenticatedItemsNewRoute: typeof AuthenticatedItemsNewRoute
  AuthenticatedItemsUnitsRoute: typeof AuthenticatedItemsUnitsRoute
  AuthenticatedLogisticsDeliveryHistoryRoute: typeof AuthenticatedLogisticsDeliveryHistoryRoute
  AuthenticatedLogisticsIncomingOrdersRoute: typeof AuthenticatedLogisticsIncomingOrdersRoute
  AuthenticatedLogisticsReadyToDeliverRoute: typeof AuthenticatedLogisticsReadyToDeliverRoute
  AuthenticatedPurchasingPurchaseOrdersRoute: typeof AuthenticatedPurchasingPurchaseOrdersRoute
  AuthenticatedPurchasingStockReceivingRoute: typeof AuthenticatedPurchasingStockReceivingRoute
  AuthenticatedPurchasingSuppliersRoute: typeof AuthenticatedPurchasingSuppliersRoute
  AuthenticatedSalesClientsRoute: typeof AuthenticatedSalesClientsRoute
  AuthenticatedSalesClientsAnalyticsRoute: typeof AuthenticatedSalesClientsAnalyticsRoute
  AuthenticatedSalesCofsRoute: typeof AuthenticatedSalesCofsRoute
  AuthenticatedSalesDiscountsRoute: typeof AuthenticatedSalesDiscountsRoute
  AuthenticatedSalesDispatchRoute: typeof AuthenticatedSalesDispatchRoute
  AuthenticatedSalesIntakeRoute: typeof AuthenticatedSalesIntakeRoute
  AuthenticatedSalesItemsRoute: typeof AuthenticatedSalesItemsRoute
  AuthenticatedSalesItemsExpiryRoute: typeof AuthenticatedSalesItemsExpiryRoute
  AuthenticatedSuperAdminBranchDashboardsRoute: typeof AuthenticatedSuperAdminBranchDashboardsRoute
  AuthenticatedSuperAdminBranchesRoute: typeof AuthenticatedSuperAdminBranchesRoute
  AuthenticatedSuperAdminClientsRoute: typeof AuthenticatedSuperAdminClientsRoute
  AuthenticatedSuperAdminCompanyAnalyticsRoute: typeof AuthenticatedSuperAdminCompanyAnalyticsRoute
  AuthenticatedSuperAdminCompareBranchesRoute: typeof AuthenticatedSuperAdminCompareBranchesRoute
  AuthenticatedSuperAdminPurchasesOverviewRoute: typeof AuthenticatedSuperAdminPurchasesOverviewRoute
  AuthenticatedSuperAdminRoleAssignmentRoute: typeof AuthenticatedSuperAdminRoleAssignmentRoute
  AuthenticatedSuperAdminSalesOverviewRoute: typeof AuthenticatedSuperAdminSalesOverviewRoute
  AuthenticatedItemsIndexRoute: typeof AuthenticatedItemsIndexRoute
  AuthenticatedItemsItemIdEditRoute: typeof AuthenticatedItemsItemIdEditRoute
  AuthenticatedItemsItemIdIndexRoute: typeof AuthenticatedItemsItemIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUnauthorizedRoute: AuthenticatedUnauthorizedRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountingClientPricingRoute:
    AuthenticatedAccountingClientPricingRoute,
  AuthenticatedAccountingItemsRoute: AuthenticatedAccountingItemsRoute,
  AuthenticatedAccountingPaymentHistoryRoute:
    AuthenticatedAccountingPaymentHistoryRoute,
  AuthenticatedAccountingPendingPaymentsRoute:
    AuthenticatedAccountingPendingPaymentsRoute,
  AuthenticatedAccountingPendingPricingRoute:
    AuthenticatedAccountingPendingPricingRoute,
  AuthenticatedAdminActivityLogRoute: AuthenticatedAdminActivityLogRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminClientAccountsRoute: AuthenticatedAdminClientAccountsRoute,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRoute,
  AuthenticatedAdminRolePermissionsRoute:
    AuthenticatedAdminRolePermissionsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedInventoryExpiringRoute: AuthenticatedInventoryExpiringRoute,
  AuthenticatedInventoryLowStockRoute: AuthenticatedInventoryLowStockRoute,
  AuthenticatedItemsCategoriesRoute: AuthenticatedItemsCategoriesRoute,
  AuthenticatedItemsNewRoute: AuthenticatedItemsNewRoute,
  AuthenticatedItemsUnitsRoute: AuthenticatedItemsUnitsRoute,
  AuthenticatedLogisticsDeliveryHistoryRoute:
    AuthenticatedLogisticsDeliveryHistoryRoute,
  AuthenticatedLogisticsIncomingOrdersRoute:
    AuthenticatedLogisticsIncomingOrdersRoute,
  AuthenticatedLogisticsReadyToDeliverRoute:
    AuthenticatedLogisticsReadyToDeliverRoute,
  AuthenticatedPurchasingPurchaseOrdersRoute:
    AuthenticatedPurchasingPurchaseOrdersRoute,
  AuthenticatedPurchasingStockReceivingRoute:
    AuthenticatedPurchasingStockReceivingRoute,
  AuthenticatedPurchasingSuppliersRoute: AuthenticatedPurchasingSuppliersRoute,
  AuthenticatedSalesClientsRoute: AuthenticatedSalesClientsRoute,
  AuthenticatedSalesClientsAnalyticsRoute:
    AuthenticatedSalesClientsAnalyticsRoute,
  AuthenticatedSalesCofsRoute: AuthenticatedSalesCofsRoute,
  AuthenticatedSalesDiscountsRoute: AuthenticatedSalesDiscountsRoute,
  AuthenticatedSalesDispatchRoute: AuthenticatedSalesDispatchRoute,
  AuthenticatedSalesIntakeRoute: AuthenticatedSalesIntakeRoute,
  AuthenticatedSalesItemsRoute: AuthenticatedSalesItemsRoute,
  AuthenticatedSalesItemsExpiryRoute: AuthenticatedSalesItemsExpiryRoute,
  AuthenticatedSuperAdminBranchDashboardsRoute:
    AuthenticatedSuperAdminBranchDashboardsRoute,
  AuthenticatedSuperAdminBranchesRoute: AuthenticatedSuperAdminBranchesRoute,
  AuthenticatedSuperAdminClientsRoute: AuthenticatedSuperAdminClientsRoute,
  AuthenticatedSuperAdminCompanyAnalyticsRoute:
    AuthenticatedSuperAdminCompanyAnalyticsRoute,
  AuthenticatedSuperAdminCompareBranchesRoute:
    AuthenticatedSuperAdminCompareBranchesRoute,
  AuthenticatedSuperAdminPurchasesOverviewRoute:
    AuthenticatedSuperAdminPurchasesOverviewRoute,
  AuthenticatedSuperAdminRoleAssignmentRoute:
    AuthenticatedSuperAdminRoleAssignmentRoute,
  AuthenticatedSuperAdminSalesOverviewRoute:
    AuthenticatedSuperAdminSalesOverviewRoute,
  AuthenticatedItemsIndexRoute: AuthenticatedItemsIndexRoute,
  AuthenticatedItemsItemIdEditRoute: AuthenticatedItemsItemIdEditRoute,
  AuthenticatedItemsItemIdIndexRoute: AuthenticatedItemsItemIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
